nameOverride: prod-ride
fullnameOverride: prod-ride

# These global values are used by all components of the application.
global:
  vault:
    licenceplate: f4dbc3 # This is the license plate you are deploying to. It is used to determine the vault path
    environment: prod #Set to prod if you want to use the prod vault or nonprod for dev/test/uat
  route:
    ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP
  release: # This is set by Github actions for the prod release. Do not change this value.

webapp:
  component: webapp # Used for the selector label as well as appended to the nameOverride and fullnameOverride in various components
  allowExternalIngress: true # Set to false if you do not want external traffic to reach the app
  replicaCount: 2 # Number of replicas to deploy

  image:
    repository: ghcr.io/bcgov/ride-webapp
    tag: latest-uat

  prometheus:
    enabled: false # If you have prometheus metrics in the app, set to true so sysdig can scrape them.

  vault:
    secretName: prod-webapp  # This is the name of the secret in vault that contains the environment variables for the app
    authPath: auth/k8s-gold # Must match cluster. Use one of: k8s-silver, k8s-gold, k8s-golddr, k8s-emerald

  deployment:
    strategy: RollingUpdate # Can be Recreate or RollingUpdate
    resources:
      requests:
        cpu: 10m
        memory: 75Mi
      limits:
        memory: 300Mi
    env:
      postgresSecret: prod-ride-db-crunchy-pguser-prod-ride-db # This is the name of the secret generated by Crunchy for the database
      variables:
        SHOW_DEBUG_TOOLBAR: 'True' # Set to False for UAT and Prod
        DEBUG: 'True' # Set to False for UAT and Prod

  route:
    host: prod-ride.apps.gold.devops.gov.bc.ca # The host name for the route
    iprestricted: true #Set to true if you want to limit IP's the the addresses in the ipallowlist in the global section. Applies to above url and vanity url
    # NOTE: For Vanity URL, this will only do the initial install of the URL. Once created it WILL NOT update it or delete it. This must be done manually
    # because you would most likely have set a certificate on the route and updating it or deleting it could cause issues.
    vanityurl: true #Set to true if you want to use a vanity URL. This will require a certificate in the cluster (set manually) and dns entry
    vanityurlhost: ride.th.gov.bc.ca  #The path to use for the vanity URL

  podDisruptionBudget: 
    enabled: true # If you have more than 1 replica, you can set this to true. Will also check to ensure more than 1 replica set to prevent issues
    minAvailable: 1 