name: 1. Build standbycheck
# Based on: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

#Will automatically run on a push to main, but can also be run manually
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  WEBAPP_IMAGE_NAME: ${{ github.repository }}-standbycheck

jobs:
  build-and-push-webapp:
    runs-on: ubuntu-latest
    name: Build & Push Webapp Image
    environment: dev
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.WEBAPP_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=latest-dev
            type=sha,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./compose/standbycheck/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            DEBUG_BUILD=true
