# This workflow is to update Crunchy using Github actions

name: Crunchy DB Update

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      cluster:
        type: choice
        description: OpenShift Cluster
        options: 
        - gold
        - golddr

jobs:
  update-openshift:
    runs-on: ubuntu-latest
    name: Deploy Latest Helm Chart to ${{ github.event.inputs.cluster }} on ${{ github.event.inputs.environment }}
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
          
    - name: Authenticate and set context for Gold
      if: ${{ github.event.inputs.cluster == 'gold' }}
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLD_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLD_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Helm upgrade on OpenShift ${{ github.event.inputs.environment }} Environment
      run: |
        helm upgrade ${{ github.event.inputs.environment }}-ride-db -f ./infrastructure/crunchy-postgres/values-${{ github.event.inputs.environment }}-${{ github.event.inputs.cluster }}.yaml ./infrastructure/crunchy-postgres  --set crunchy.pgBackRest.s3.bucket=${{ secrets.CRUNCHY_BUCKET }} --set crunchy.pgBackRest.s3.endpoint=${{ secrets.CRUNCHY_ENDPOINT }}


    - name: Authenticate and set context for GoldDR
      if: ${{ github.event.inputs.cluster == 'golddr' }}
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLDDR_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLDDR_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Helm upgrade on OpenShift ${{ github.event.inputs.environment }} Environment
      run: |
        helm upgrade ${{ github.event.inputs.environment }}-ride-db -f ./infrastructure/crunchy-postgres/values-${{ github.event.inputs.environment }}-gold.yaml -f ./infrastructure/crunchy-postgres/values-${{ github.event.inputs.environment }}-golddr.yaml ./infrastructure/crunchy-postgres  --set crunchy.pgBackRest.s3.bucket=${{ secrets.CRUNCHY_BUCKET }} --set crunchy.pgBackRest.s3.endpoint=${{ secrets.CRUNCHY_ENDPOINT }}

