name: 3. Build & Deploy to UAT

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  WEBAPP_IMAGE_NAME: ${{ github.repository }}-webapp

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Create Tag and set Variable
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.create_tag.outputs.tag }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Incremental Tag
      id: generate_tag
      run: |
        # Fetch existing tags
        git fetch --tags
        
        # Find the highest existing "b" tag number
        LAST_RUN_ID=$(git tag -l "rc*" | sed -E "s/rc//" | sort -n | tail -n 1)
        
        # Default to 0 if no previous run ID found
        if [ -z "$LAST_RUN_ID" ]; then
          LAST_RUN_ID=0
        fi
        
        # Increment run ID
        RUN_ID=$((LAST_RUN_ID + 1))
        TAG="rc${RUN_ID}"
        
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Create Tag
      id: create_tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git tag ${{ steps.generate_tag.outputs.tag }}
        git push origin ${{ steps.generate_tag.outputs.tag }}
        echo "tag=${{ steps.generate_tag.outputs.tag }}" >> $GITHUB_OUTPUT

    - name: Display Tag Name
      run: |
        echo "Tag Name: ${{ steps.create_tag.outputs.tag }}"

  build-and-push-webapp:
    needs: [tag]
    runs-on: ubuntu-latest
    name: Build & Push Webapp Image
    environment: uat
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.WEBAPP_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=latest-uat
            type=sha,format=long
            type=raw,value=${{ needs.tag.outputs.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./compose/webapp/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            DEBUG_BUILD=false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-openshift-gold:
    needs: [tag, build-and-push-webapp]
    runs-on: ubuntu-latest
    name: Deploy Latest Image (${{ needs.tag.outputs.tag }}) to OpenShift Gold
    environment:
      name: uat
      url: https://uat-ride.apps.gold.devops.gov.bc.ca
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
      
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLD_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLD_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true
    - name: Helm upgrade on OpenShift Gold Environment
      run: |
        helm upgrade uat-ride -f ./infrastructure/helm/values-uat-gold.yaml ./infrastructure/helm --set webapp.image.tag="${{ needs.tag.outputs.tag }}"

  # I have this run after the push to Gold because I want to make sure that Gold runs the migrations first. Gold DR can't run migrations as DB is read-only
  update-openshift-golddr:
    needs: [tag, update-openshift-gold] 
    runs-on: ubuntu-latest
    name: Deploy Latest Image (${{ needs.tag.outputs.tag }}) to OpenShift GoldDR
    environment:
      name: uat
      url: https://uat-ride.apps.golddr.devops.gov.bc.ca
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
     
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLDDR_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLDDR_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Helm upgrade on OpenShift GoldDR Environment
      run: |
        helm upgrade uat-ride -f ./infrastructure/helm/values-uat-gold.yaml -f ./infrastructure/helm/values-uat-golddr.yaml ./infrastructure/helm --set webapp.image.tag="${{ needs.tag.outputs.tag }}"