# Generated by Django 5.1.5 on 2025-02-05 20:37

import django.contrib.gis.db.models.fields
import django.core.serializers.json
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('event_type', models.CharField(choices=[('CONSTRUCTION', 'Construction'), ('INCIDENT', 'Incident'), ('SPECIAL_EVENT', 'Special Event'), ('WEATHER_CONDITION', 'Weather Condition'), ('ROAD_CONDITION', 'Road Condition')], max_length=30)),
                ('event_subtype', models.CharField(choices=[('ALMOST_IMPASSABLE', 'Almost Impassable'), ('FIRE', 'Fire'), ('HAZARD', 'Hazard'), ('ROAD_CONSTRUCTION', 'Road Construction'), ('ROAD_MAINTENANCE', 'Road Maintenance'), ('PARTLY_ICY', 'Partly Icy'), ('ICE_COVERED', 'Ice Covered'), ('SNOW_PACKED', 'Snow Packed'), ('PARTLY_SNOW_PACKED', 'Partly Snow Packed'), ('MUD', 'Mud'), ('PLANNED_EVENT', 'Planned Event'), ('POOR_VISIBILITY', 'Poor Visibility'), ('PARTLY_SNOW_COVERED', 'Partly Snow Covered'), ('DRIFTING_SNOW', 'Drifting Snow'), ('PASSABLE_WITH_CARE', 'Passable With Care')], max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major')], max_length=20)),
                ('is_closure', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('description', models.TextField()),
            ],
        ),
    ]
