# Generated by Django 5.1.5 on 2025-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='headline',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
