# Generated by Django 5.1.5 on 2025-02-10 21:12

import django.contrib.gis.db.models.fields
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='event',
            name='metadata',
            field=models.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
