# Generated by Django 5.1.5 on 2025-02-10 23:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_geometry_alter_event_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
