# Generated by Django 5.1.5 on 2025-02-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_subtype',
            field=models.CharField(choices=[('ALMOST_IMPASSABLE', 'Almost impassable'), ('FIRE', 'Fire'), ('HAZARD', 'Hazard'), ('ROAD_CONSTRUCTION', 'Road construction'), ('ROAD_MAINTENANCE', 'Road maintenance'), ('PARTLY_ICY', 'Partly icy'), ('ICE_COVERED', 'Ice covered'), ('SNOW_PACKED', 'Snow packed'), ('PARTLY_SNOW_PACKED', 'Partly snow packed'), ('MUD', 'Mud'), ('PLANNED_EVENT', 'Planned event'), ('POOR_VISIBILITY', 'Poor visiblity'), ('PARTLY_SNOW_COVERED', 'Partly snow packed'), ('DRIFTING_SNOW', 'Drifting snow'), ('PASSABLE_WITH_CARE', 'Passable with care')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CONSTRUCTION', 'Construction'), ('INCIDENT', 'Incident'), ('SPECIAL_EVENT', 'Special event'), ('WEATHER_CONDITION', 'Weather condition'), ('ROAD_CONDITION', 'Road condition')], max_length=30),
        ),
    ]
